### ISSUE TITLE
热水器加载不成功

### ISSUE THREAD

**Issue by fbi007130** [baranwang/homebridge-plugin-haier#43]
[11/20/2024, 9:17:06 AM] [HaierHomebridgePlugin] Restoring existing accessory from cache: 客厅 - 电热水器
[11/20/2024, 9:17:06 AM] [HaierHomebridgePlugin] request: https://uws.haier.net/shadow/v1/devdigitalmodels { deviceInfoList: [ { deviceId: 'D8E23F8A3***' }, [length]: 1 ] }
[11/20/2024, 9:17:06 AM] [HaierHomebridgePlugin] Executed shutdown callback

**Comment by fbi007130** [comment]
[11/30/2024, 1:49:37 PM] [@hb-haier/homebridge-plugin] This plugin generated a warning from the characteristic 'Target Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[11/30/2024, 1:49:37 PM] TypeError: Cannot read properties of undefined (reading 'valueRange')
    at HotWaterAccessory.get targetTemperatureProps [as targetTemperatureProps] (/homebridge/node_modules/@hb-haier/homebridge-plugin/src/accessories/hot-water.ts:75:71)
    at HotWaterAccessory.init (/homebridge/node_modules/@hb-haier/homebridge-plugin/src/accessories/hot-water.ts:44:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
更多log
